### ISSUE TITLE
"not" operator doesn't have an effect

### ISSUE THREAD

**Issue by jpk15211** [nickovic/rtamt4ros#1]
I've seen examples where the "not" operator has no effect on the monitoring result. For example, consider the [ros_stl_monitor.launch](https://github.com/nickovic/rtamt4ros/blob/master/rtamt4ros/launch/ros_stl_monitor.launch) example launch file, which uses the [spec.stl](https://raw.githubusercontent.com/nickovic/rtamt4ros/master/rtamt4ros/specs/spec.stl) specification. If I change the existing specification
`c.value = always (a.value <= 2)`
by adding a not after always, like so
`c.value = always not (a.value <= 2)`
I get the same resulting robustness value output.

**Comment by TomyYamy** [comment]
I think it is now rtamt side issue.

**Comment by TomyYamy** [comment]
I checked it with current rtamt 1b0f010.
"not" works in rtamt.STLDenseTimeSpecification() class.
