### ISSUE TITLE
String variable as output

### ISSUE THREAD

**Issue by julendelarco** [nickovic/rtamt4ros#18]
Hi all,

I am trying to use your code for creating a monitor and I came up with a doubt. I would really appreciate your help. 

My idea is to output a custom message where a name (string) and the robustness value (float) are sent. 

    spec.name ='HandMadeMonitor'
    spec.import_module('monitor_msgs.msg', 'MonitorMessage')
    spec.import_module('nav_msgs.msg', 'Odometry')

    spec.declare_var('pos', 'Odometry')
    spec.declare_var('out', 'MonitorMessage')
    spec.set_var_topic('pos', '/vesc/odom')
    spec.set_var_topic('out', 'monitor/out')
    spec.spec = 'out.name = test'
    spec.spec = 'out.value = ( (0<pos.pose.pose.position.x<100) and (0<pos.pose.pose.position.y<50) )'

These are the only changes I have done to the code. Everything is working except the "spec.spec = 'out.name = test'" line. It does not assign "test" as name to the output variable. **Is it possible to do this? And, if so, how would it be possible to do this correctly?**

_More info:
This is the message I am getting from the output topic ('monitor/out'). Note that the name is empty:_
![image](https://user-images.githubusercontent.com/39483858/116079736-74d09a80-a698-11eb-8d19-172dac1fbae3.png)

_And this is the MonitorMessage structure:_
Header header
string name
float64 value

**Comment by nickovic** [comment]
In the current implementation of RTAMT, there can be only one main specification and RTAMT is supposed only to update real-valued fields of a message (corresponding to the computed robustness). You should update the other fields of your MonitorMessage outside of RTAMT.

Note that RTAMT4ROS is a ROS wrapper around RTAMT that illustrates a possible integration of RTAMT with ROS. For relatively simple scenarios, it can be used as it is, but in your scenario I would suggest slightly adapting the wrapper to update the name field accordingly.
